(package "popup"
         "0.5.9"
         "Visual Popup User Interface")

(website-url "https://github.com/auto-complete/popup-el")
(keywords "lisp")

(package-file "popup.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "melpa")

(depends-on "emacs" "24.3")

(development
 (depends-on "ert"))

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
